// separate from save.ts to avoid circular deps

export type SaveFile = {
    // GH fields
    repo: string; // repo full name
    name: string; // user-editable name (defaults to repo name)
    summary: string; // original repository summary
    description: string; // user-editable description
    // system fields
    order: number; // order in the list
    // custom fields
    [key: `c_${string}`]: string | boolean;
}[];

// copied for better intellisense in config file
export type SaveFilePublic = ({
    // GH fields
    repo: string; // repo full name
    name: string; // user-editable name (defaults to repo name)
    summary: string; // original repository summary
    description: string; // user-editable description
    // system fields
    order: number; // order in the list
} & Record<string, string | boolean>)[];

export const saveObjectToString = (save: SaveFile) => `/* DO NOT EDIT THIS FILE. Use \`ghcms edit start\`, then \`ghcms edit commit\` to save changes. */${JSON.stringify(save)}`;
export const stringToSaveObject = (save: string) => /* remove the comment first by removing everything up to first [ */ JSON.parse(save.slice(save.indexOf("[")));
